variables:
  REPOSITORY_OF_PIPELINE_IMAGES: darkwind8/temp
  CI_BUILDER_IMAGE: ci-v1

stages:
  - build_and_push

build_ci_image:
  image: docker:20.10.12-alpine3.15
  stage: build_and_push
  variables:
    DOCKER_HOST: tcp://dind-service:2375
  script:
      - docker ps
      - mkdir ~/.docker; echo "$dockerconfig_darkwind8" > ~/.docker/config.json
      - docker build --tag $REPOSITORY_OF_PIPELINE_IMAGES:$CI_BUILDER_IMAGE ci
      - docker push $REPOSITORY_OF_PIPELINE_IMAGES:$CI_BUILDER_IMAGE