FROM docker:20.10.12-alpine3.15

WORKDIR /install

RUN apk update
RUN apk add --no-cache wget
RUN apk add --no-cache curl

RUN curl -LO https://dl.k8s.io/release/v1.22.8/bin/linux/amd64/kubectl
RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
RUN kubectl version --client

RUN wget https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz
RUN tar -xf helm-v3.9.0-linux-amd64.tar.gz
RUN mv linux-amd64/helm /usr/local/bin/helm

RUN wget https://github.com/digitalocean/doctl/releases/download/v1.77.0/doctl-1.77.0-linux-amd64.tar.gz
RUN tar xf doctl-1.77.0-linux-amd64.tar.gz
RUN mv doctl /usr/local/bin
RUN doctl version

ENV PYTHONUNBUFFERED=1
RUN apk add python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --upgrade pip setuptools

RUN apk add --update openssl && \
    rm -rf /var/cache/apk/*

WORKDIR /app
